spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb+srv://usertest:g4X57kKqP4w8c4yz@cluster0-wftcr.mongodb.net/test?retryWrites=true&w=majority
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /management
      exposure:
        include: info, health, metrics

